# Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [4]:
a[0] = 5
print(a)

[5 2 3]


In [5]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [6]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [7]:
b = np.ones((1, 2))
print(b)

[[1. 1.]]


In [8]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [9]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [11]:
e = np.random.random((2, 2))
print(e)

[[0.50471775 0.62971575]
 [0.40107155 0.10437683]]


#Array indexing

### Slicing

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
b = a[:2, 1:3]
print(b)
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r1, row_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[5 6 7 8] (1, 4)


In [16]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing

In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])

[ 1  6  7 11]


In [21]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing

In [23]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# Datatypes

In [24]:
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2], dtype = np.int64)
print(x.dtype)

int64
float64
int64


# Array math

In [25]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [26]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [27]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [28]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [30]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [32]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [33]:
print(v.dot(w))
print(np.dot(v, w)) # 내적

219
219


In [34]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [35]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [36]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis = 0)) # 열끼리 더하기
print(np.sum(x, axis = 1)) # 행끼리 더하기

10
[4 6]
[3 7]


In [37]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [38]:
v = np.array([1, 2, 3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


# Broadcasting

In [44]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
print(x)
print(v)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
for i in range(4):
  y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [45]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [46]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [48]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [49]:
v = np.array([1, 2, 3])
w = np.array([4, 5])
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [50]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [51]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [52]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


# Distance between points

In [53]:
from scipy.spatial.distance import pdist, squareform
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]
